(*
 * This is an interface file
 * It's normally generated by make and is called Graph
 * However, with BS we cannot configure it in such a way
 * that Graph doesn't shadow other modules called Graph
 * in this project.
 * Because of this, there's a patch in the main
 * bucklescript-opam-core repo
 *)
module Builder = Builder
module ChaoticIteration = ChaoticIteration
module Classic = Classic
module Clique = Clique
module Cliquetree = Cliquetree
module Coloring = Coloring
module Components = Components
module Contraction = Contraction
module Delaunay = Delaunay
module Dominator = Dominator
module Dot = Dot
module Dot_ast = Dot_ast
module Fixpoint = Fixpoint
module Flow = Flow
module Gmap = Gmap
module Gml = Gml
module Graphml = Graphml
module Graphviz = Graphviz
module Imperative = Imperative
module Kruskal = Kruskal
module Leaderlist = Leaderlist
module Mcs_m = Mcs_m
module Md = Md
module Merge = Merge
module Mincut = Mincut
module Minsep = Minsep
module Nonnegative = Nonnegative
module Oper = Oper
module Pack = Pack
module Path = Path
module Persistent = Persistent
module Prim = Prim
module Rand = Rand
module Sig = Sig
module Sig_pack = Sig_pack
module Strat = Strat
module Topological = Topological
module Traverse = Traverse
module Util = Util
module WeakTopological = WeakTopological
module Bitv = Bitv
module Heap = Heap
module PersistentQueue = PersistentQueue
module Unionfind = Unionfind
